image:
  repository: docker.io/istio/examples-bookinfo-ratings-v1
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.16.4"